#!/bin/sh

if [ $(uname -s) = "Linux" ]; then
    PATH=/usr/local/go/bin:$PATH
fi
PATH=~/bin:$PATH
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=~/go/bin:$PATH
PATH=~/.krew/bin/:$PATH
PATH=~/.cargo/bin:$PATH
PATH=~/.npm-packages/bin:$PATH
PATH=~/.local/bin:$PATH
export PATH

unset MANPATH
export MANPATH=~/.npm-packages/share/man:$(manpath)
