import = [".config/alacritty/tokyonight_night.toml"]

[font]
size = 12
normal.family = "BlexMono Nerd Font"
normal.style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
opacity = 0.95
