
[font]
size = 12
normal.family = "BlexMono Nerd Font"
normal.style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
opacity = 0.95
# remember you like to double click on the title to fullscreen
# decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[general]
import = ["~/.config/alacritty/tokyonight_night.toml"]
